fix(cli): remove invalid conflicts_with (#447)
Attempting `soroban contract read` currently fails with:

    thread 'main' panicked at 'Command read: Argument or group 'rpc-url' specified in 'conflicts_with*' for 'ledger-file' does not exist', /Users/chadoh/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.23/src/builder/debug_asserts.rs:237:13

This fixes it.

Co-authored-by: Paul Bellamy <paul@stellar.org>