Create dynamic args from XDR and parse normal JSON (#307)
* feat: add `args-file` option to `invoke`

Currently only tests raw string

* chore: fmt

* fix: deploy test contract once and invoke twice

* fix: test and arg type

* feat: add `args-xdr-file`

rename matches to arg_matches since matches is keyword

* chore: add more tests

* Merge remote-tracking branch 'origin/main' into feat/args_file_cmd

* chore: remove `s`'s to be more consistent

* fix: find test files and update error message

* chore: fmt

* chore: clippy

* fix: Find arg file fixture

* chore: fmt

* chore: improve wasm and spec reading

* feat: create dynamic Args from xdr and parse slop

Args after `--` are treated as arguments to a dynamic Args type generated from xdr.

* Remove crate-git-revision 0.0.3 from dep graph

* feat: first steps at better JSON input

* feat: remove args option parsing and use new slop instead

* feat: simple enum

* feat!: remove arg match througout

* chore: use thiserror for StrValError

* fix: rename Error type to be more idiomatic

* Delete build.rs

* feat: move json parsing into strval; add Spec type to handle lookups

`Spec` also handles parsing so that complex types can lookup types referenced

* chore: cleanup

* feat: complex enums and reorg for better readability and maintainability

* chore: reorg arg builder to assume string parser

The builder will over write any new parser and most new args will assume to be string parsers.

* fix: check if bool is present instead of getting value

* fix: force all types to go through json parsing

* chore: add more test functions for builtin types

* feat: add support for tuple structs and const enums

And add tests

* chore: test different return vals

* chore: fmt and clippy

clippy suggested I deal with the truncating u64 and it led to a new error!

* feat: improve XDR -> JSON and add tests

* chore: fmt

* fix: parse test

* fix: e2e test

* fix: fmt

* chore: fmt again?

* fix: arg name is `world`

* fix: clippy

* fix: sandbox test

* fix: clippy on tests

* fix: e2e test result

* fix: e2e outdated hash

* chore: reuse the install command when deploying and installing

Also update salt so tests won't collide.

* chore: clippy

* fix: use hash server expects

* fix: remove salt option to pass e2e

* refactor: mv arg-parse tests to integration dir

Like the `tests/it/custom_types.rs` tests, these arg-parsing tests rely
on the `target/wasm32-unknown-unknown/test-wasms/test_custom_types.wasm`
file.

But the lookup logic for the `test-wasms` files in the integration test
directory was far superior, throwing a useful message about how you need
to run `make build-test-wasms` if the files are not found. And
unfortunately, unit tests run before integration tests, so the nice
message was never seen, and instead we ended up with errors like:

    thread 'contract::invoke::test::parse_enum' panicked at 'called
    `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound,
    message: "No such file or directory" }',
    cmd/soroban-cli/src/contract/invoke.rs:715:18

I wanted to reuse the nice test-wasms lookup logic, rather than
copy-pasting.

The arg-parsing tests were contained within `invoke.rs`, but they made
no use of anything in the `invoke.rs` file. They were fairly clean to
move, with one big exception: they require importing `strval`!

To import `strval` in the integration tests, I had to add a `lib.rs`, so
that the integration tests can import things directly from the main
library, rather than only using the built binary.

The CLI is written in such a way that it could become a useful library,
in addition to being a binary. Are the current exports the most useful
as part of this library? I doubt it, but they were what I needed to
export in order to move these tests. I'm not sure if it's worth fleshing
out the "library" at this time.

* refactor: no need for public run

* refactor: rm needless `pub` declarations in main.rs

these were added in 1311d2181624fa804c6d0521677ad381584c71f4 while
figuring out how to get main.rs + lib.rs working together, but were not
needed

* refactor: appease pedantic clippy

Mostly clippy wanted real docs. I gave it fake docs just to make it
pass. We should fill in real docs though!

* build: update to stellar/system-test:1.0.2

Co-authored-by: Leigh McCulloch <351529+leighmcculloch@users.noreply.github.com>
Co-authored-by: Chad Ostrowski <221614+chadoh@users.noreply.github.com>